//the following code was generated by Android Studio
package com.edward_costache.stay_fitrpg;

import android.app.Application;
//the code above was generated by Android Studio

/**
 * Created by Edward Costache
 */
public class BaseApplication extends Application {

    @Override
    public void onCreate() {
        super.onCreate();
    }
}
