//the following code was generated by Android Studio
package com.edward_costache.stay_fitrpg;

import java.util.HashMap;
//the code above was generated by Android Studio

/**
 * A class for defining a ProgressWeek, which has a name, and a HashMap of days.
 *
 * Created by Edward Costache
 */
public class ProgressWeek {
    private String weekName;
    private String weekID;
    private HashMap<String, ProgressDay> days;

    //Empty constructed needed for FirebaseDatabase ValueEventListeners
    ProgressWeek()
    {

    }

    ProgressWeek(String weekName, HashMap<String, ProgressDay> days, String weekID)
    {
        setWeekName(weekName);
        setDays(days);
        setWeekID(weekID);
    }

    public String getWeekName() {
        return weekName;
    }

    public void setWeekName(String weekName) {
        this.weekName = weekName;
    }

    public HashMap<String, ProgressDay> getDays() {
        return days;
    }

    public void setDays(HashMap<String, ProgressDay> days) {
        this.days = days;
    }

    public String getWeekID() {
        return weekID;
    }

    public void setWeekID(String weekID) {
        this.weekID = weekID;
    }
}
